version: '3.8'

services:
  test-automation:
    build: .
    container_name: test-automation-framework
    environment:
      - HEADLESS=true
      - BROWSER=chrome
      - API_BASE_URL=https://jsonplaceholder.typicode.com
      - UI_BASE_URL=https://www.saucedemo.com
    volumes:
      - ./target:/app/target
      - ./allure-results:/app/target/allure-results
    networks:
      - test-network

  allure-server:
    image: frankescobar/allure-docker-service
    container_name: allure-server
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    networks:
      - test-network
    depends_on:
      - test-automation

  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - test-network

  chrome:
    image: selenium/node-chrome:4.15.0
    container_name: chrome-node
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    networks:
      - test-network

  firefox:
    image: selenium/node-firefox:4.15.0
    container_name: firefox-node
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    networks:
      - test-network

networks:
  test-network:
    driver: bridge