name: 🧪 API Tests Only

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-tests:
    name: 🧪 API Tests Only
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: ☕ Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: 📦 Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: 🔨 Compile project
      run: mvn clean compile test-compile
      
    - name: 🧪 Run API tests
      run: mvn test -Dtest="*Api*" -Dsurefire.failIfNoSpecifiedTests=false
      
    - name: 🧪 Run E2E API tests
      run: mvn test -Dtest="*E2E*" -Dsurefire.failIfNoSpecifiedTests=false
      continue-on-error: true
      
    - name: 🧪 Run Data-driven API tests
      run: mvn test -Dtest="*DataDriven*" -Dsurefire.failIfNoSpecifiedTests=false
      continue-on-error: true
      
    - name: 📊 Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-test-results
        path: |
          target/surefire-reports/
          target/allure-results/
          
    - name: 📊 Generate Allure Report
      if: always()
      run: |
        # Install Allure
        wget -q https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.0/allure-commandline-2.29.0.zip -O /tmp/allure.zip
        unzip /tmp/allure.zip -d /opt/allure
        sudo ln -s /opt/allure/allure-2.29.0/bin/allure /usr/bin/allure
        sudo chmod +x /usr/bin/allure
        
        # Generate report
        allure generate target/allure-results --clean -o allure-report
        
    - name: 📤 Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        
    - name: 🚀 Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        force_orphan: true
