name: ⚡ Quick Test (Optimized)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/test/java/api/**'
      - 'src/test/java/ui/**'
      - 'src/test/java/e2e/**'

jobs:
  quick-test:
    name: 🧪 Quick Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: ☕ Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: 🔨 Compile project
      run: mvn clean compile test-compile
      
    - name: 🧪 Run API tests
      run: mvn test -Dtest="api.SimpleApiTest,api.WorkingApiTest" -Dheadless=true
      continue-on-error: true
      
    - name: 🧪 Run UI tests (headless)
      run: mvn test -Dtest="ui.SimpleUiTest,ui.WorkingUiTest" -Dheadless=true
      continue-on-error: true
      
    - name: 📊 Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: quick-test-results
        path: |
          target/surefire-reports/
          target/allure-results/
